spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job_management
    username: root
    password: cwcasd456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true