spring:
  datasource:
    url: jdbc:mysql://xxx.xxx.xxx.xxx:3306/job_management
    username: xxx
    password: xxx
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true